
#include <miniweb/modules/man.h>

/**
 * @brief Execute a manual-page search request.
 *
 * @param query Search token provided by the API caller.
 *
 * @return char* Heap-allocated response body generated by man search helpers.
 */
char *
man_service_search_json(const char *query)
{
	return man_api_search(query);
}
